### ISSUE TITLE
Another NPE

### ISSUE THREAD

**Issue by PancakeZik** [dkilgore90/google-sdm-api#17] opened 2020-10-08 05:57 UTC
When I turn on event subscriptions, after a minute or so my logs start getting spammed with this. These messages repeat every second or so until I turn off subscription again. 

app:4832020-10-08 06:55:54.721 errorjava.lang.NullPointerException: null (postEvents)
app:4832020-10-08 06:55:54.715 debug{
  "eventId": "c119376b-a5b6-4a10-b782-23853f608ffc",
  "timestamp": "2020-10-08T05:55:25.693Z",
  "resourceUpdate": {
    "name": "enterprises/94b4ad03-484f-44bd-99a3-6753dd42e6d7/devices/AVPHwEu8XSnGXYxAuOBVDOnonXUSWMJt38mKr0UanQMlFRPl4KfDhk1L6ekcXjd4WHSpVdP_dArucIvemC6jmSWjnJHqKw",
    "events": {
      "sdm.devices.events.CameraMotion.Motion": {
        "eventSessionId": "AVPHwEs6ZCsb5cRDfbhTV6RNA6kwXgIdDIJ9VokQXKP6Fk8z10YX3zX7fRK95BZGmSl5s7JRMl7vX4Sr6dfA9Or_daYjGg",
        "eventId": "CiQA2vuxr_LPPBrxKT7FjS3R5ai_0-50liEZRdxIT15hkHGyd_sSwAEATD4XpwaE_g2SAfT4EQBb1tQ-0QXg8d2Ee3uEB6kMcI4LayOnHC1QsWxi3cf5gbNl6S5V1qLGLiUQ5HOg61f7jYmgsRKPxNDrvnQA0zeKlTNIchrnGriyZCoobUipo9Omrrn2vUBFBuB8xoqZExlV7XpH_OUPHNu5yYTfX7cd7Er-Vz5NaBzddY07ZCIEsbPtg-Rovd-Yt0B9TSSOWX7wG-Tn4yH7s-IOb-9YzXUOUVQYR1e8kEl9z6u-M77HJzU"
      }
    }
  },
  "userId": "AVPHwEvAiumrZc4lv01fEczozd2gPCwcU_A3XKqjaNw4"
}
app:4832020-10-08 06:55:54.707 debugevent received

**Comment by dkilgore90** [comment] 2020-10-08 12:09
Looks like a duplicate of #16

**Closed as completed by dkilgore90** 2020-10-08 12:09 UTC
Labels: bug, duplicate
